---
elasticsearch_state: present
elasticsearch_install_method: s3
elasticsearch_install_path: /opt
elasticsearch_version: 1.4.2
elasticsearch_remove_old: true
elasticsearch_s3_bucket:
elasticsearch_s3_base:
elasticsearch_user: elasticsearch
elasticsearch_path_logs: /var/log/elasticsearch
elasticsearch_path_conf: /etc/elasticsearch/conf
elasticsearch_path_work:
elasticsearch_path_plugins:
elasticsearch_path_data:
elasticsearch_java_home:
elasticsearch_autostart: true
elasticsearch_supervisor_state: started
elasticsearch_remove_old: true
#elasticsearch_plugins:
elasticsearch_max_open_files: 64000
elasticsearch_max_locked_memory: unlimited
#elasticsearch_heap_size:
#elasticsearch_heap_newsize:
#elasticsearch_direct_size:
#elasticsearch_java_opts:
#elasticsearch_cluster_name
#elasticsearch_cluster_routing_allocation_awareness_attributes
elasticsearch_node_name: "{{ inventory_hostname }}-es"
elasticsearch_node_master: 'true'
elasticsearch_node_data: 'true'
#elasticsearch_node_max_local_storage_nodes
#elasticsearch_node_extras
elasticsearch_index_number_of_shards: 5
elasticsearch_index_number_of_replicas: 1
#elasticsearch_index_translog_flush_threshold_ops:
#elasticsearch_index_memory_index_buffer_size:
elasticsearch_path_conf: /etc/elasticsearch
elasticsearch_path_data: "{{ elasticsearch_install_path }}/elasticsearch/data"
elasticsearch_path_work: "{{ elasticsearch_install_path }}/elasticsearch/work"
elasticsearch_path_logs: /var/log/elasticsearch
elasticsearch_path_plugins: "{{ elasticsearch_install_path }}/elasticsearch/plugins"
#elasticsearch_plugin_mandatory
elasticsearch_bootstrap_mlockall: 'true'
#elasticsearch_network_bind_host:
#elasticsearch_network_publish_host
elasticsearch_network_host: 0.0.0.0
elasticsearch_transport_tcp_port: '9300-9400'
elasticsearch_tcp_compress: false
elasticsearch_http_port: 9200
#elasticsearch_http_max_content_length
elasticsearch_http_enabled: 'true'
elasticsearch_gateway_type: local
#elasticsearch_gateway_recover_after_nodes
#elasticsearch_gateway_recover_after_data_nodes
#elasticsearch_gateway_recover_after_master_nodes
#elasticsearch_gateway_recover_after_time
#elasticsearch_gateway_expected_nodes
#elasticsearch_gateway_expected_data_nodes
#elasticsearch_gateway_expected_master_nodes
#elasticsearch_cluster_routing_allocation_node_concurrent_recoveries
#elasticsearch_indices_recovery_max_bytes_per_sec
#elasticsearch_indices_recovery_concurrent_stream
#elasticsearch_discovery_zen_minimum_master_nodes
elasticsearch_discovery_zen_ping_timeout: 3s
elasticsearch_discovery_zen_ping_multicast_enabled: 'true'
#elasticsearch_discovery_zen_ping_unicast_hosts
elasticsearch_script_disable_dynamic: 'false'
elasticsearch_http_cors_enabled: 'false'
#elasticsearch_http_cors_allow_origin:
#elasticsearch_plugin_aws
#elasticsearch_plugin_aws_ec2_groups
#elasticsearch_plugin_aws_availability_zones
elasticsearch_plugin_aws_any_group: 'true'
elasticsearch_plugin_aws_ec2_ping_timeout: 3s
#elasticsearch_plugin_aws_access_key
#elasticsearch_plugin_aws_secret_key
#elasticsearch_plugin_aws_region
elasticsearch_action_auto_create_index: 'true'
elasticsearch_action_disable_delete_all_indices: 'true'
#elasticsearch_conf_additional
