- name: Ensuring conf directory exists
  file: path={{ elasticsearch_path_conf }} owner={{ elasticsearch_user }} group={{ elasticsearch_user }} state=directory
  when: elasticsearch_path_conf is defined
  notify: Restart Elasticsearch

- name: Ensuring data directory exists
  file: path={{ elasticsearch_path_data }} owner={{ elasticsearch_user }} group={{ elasticsearch_user }} state=directory
  when: elasticsearch_path_data is defined
  notify: Restart Elasticsearch

- name: Ensuring work directory exists
  file: path={{ elasticsearch_path_work }} owner={{ elasticsearch_user }} group={{ elasticsearch_user }} state=directory
  when: elasticsearch_path_work is defined
  notify: Restart Elasticsearch

- name: Ensuring logs directory exists
  file: path={{ elasticsearch_path_logs }} owner={{ elasticsearch_user }} group={{ elasticsearch_user }} state=directory
  when: elasticsearch_path_logs is defined
  notify: Restart Elasticsearch

- name: Ensuring plugins directory exists
  file: path={{ elasticsearch_path_plugins }} owner={{ elasticsearch_user }} group={{ elasticsearch_user }} state=directory
  when: elasticsearch_path_plugins is defined
  notify: Restart Elasticsearch

- name: Generating elasticsearcg config file
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_path_conf }}/elasticsearch.yml
  notify: Restart Elasticsearch

- include: generic_plugins.yml

- include: ulimits.yml

